default_platform(:android)

platform :android do
    desc "Distribute build to Firebase App Distribution"
    lane :firebase do
        build_no = ENV["GITHUB_RUN_NUMBER"] || "1"

       gradle(
         task: "assemble",
         build_type: "Debug",
         properties: {
           "buildNumber" => build_no
         }
       )

      firebase_app_distribution(
        app: "1:570432063112:android:7a60d08e3de4f4c016413d",
        # 경로를 환경 변수에서 가져오거나, 못 가져오면 현재 폴더 기준 파일명을 찾도록 함
        service_credentials_file: "fastlane/service-account-key.json",
        groups: "qa",
        release_notes: "CI 자동 배포 : #{build_no}",
        debug: true,
      )
      end

      desc "Runs all the tests"
      lane :test do
        gradle(task: "test")
      end

      desc "Submit a new Beta Build to Crashlytics Beta"
      lane :beta do
        gradle(task: "clean assembleRelease")
        crashlytics

        # sh "your_script.sh"
        # You can also use other beta testing services here
      end

      desc "Deploy a new version to the Google Play"
      lane :deploy do
        gradle(task: "clean assembleRelease")
        upload_to_play_store
    end
end
