default_platform(:android)

# ENV["GOOGLE_APPLICATION_CREDENTIALS"] = File.expand_path("./fastlane/cicd-practice-21aa8-02789169dc4c.json")

platform :android do
    desc "Distribute build to Firebase App Distribution"
    lane :firebase do
      gradle(
        task: "assemble",
        build_type: "Debug"
      )

      firebase_app_distribution(
        app: "1:570432063112:android:7a60d08e3de4f4c016413d",
        service_credentials_file: "./fastlane/cicd-practice-21aa8-02789169dc4c.json",
        groups: "qa",
        release_notes: "CI 자동 배포",
        debug: true
      )
    end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
